// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.4
// source: proto/shortner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type URLtoShortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *URLtoShortRequest) Reset() {
	*x = URLtoShortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLtoShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLtoShortRequest) ProtoMessage() {}

func (x *URLtoShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLtoShortRequest.ProtoReflect.Descriptor instead.
func (*URLtoShortRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{2}
}

func (x *URLtoShortRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type URLtoShortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *URLtoShortResponse) Reset() {
	*x = URLtoShortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLtoShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLtoShortResponse) ProtoMessage() {}

func (x *URLtoShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLtoShortResponse.ProtoReflect.Descriptor instead.
func (*URLtoShortResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{3}
}

func (x *URLtoShortResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortToURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortKey string `protobuf:"bytes,1,opt,name=short_key,json=shortKey,proto3" json:"short_key,omitempty"`
}

func (x *ShortToURLRequest) Reset() {
	*x = ShortToURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortToURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortToURLRequest) ProtoMessage() {}

func (x *ShortToURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortToURLRequest.ProtoReflect.Descriptor instead.
func (*ShortToURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{4}
}

func (x *ShortToURLRequest) GetShortKey() string {
	if x != nil {
		return x.ShortKey
	}
	return ""
}

type ShortToURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullUrl string `protobuf:"bytes,1,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
}

func (x *ShortToURLResponse) Reset() {
	*x = ShortToURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortToURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortToURLResponse) ProtoMessage() {}

func (x *ShortToURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortToURLResponse.ProtoReflect.Descriptor instead.
func (*ShortToURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{5}
}

func (x *ShortToURLResponse) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

type APIShortenBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*URLMapping `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *APIShortenBatchRequest) Reset() {
	*x = APIShortenBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIShortenBatchRequest) ProtoMessage() {}

func (x *APIShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*APIShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{6}
}

func (x *APIShortenBatchRequest) GetUrls() []*URLMapping {
	if x != nil {
		return x.Urls
	}
	return nil
}

type URLMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *URLMapping) Reset() {
	*x = URLMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLMapping) ProtoMessage() {}

func (x *URLMapping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLMapping.ProtoReflect.Descriptor instead.
func (*URLMapping) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{7}
}

func (x *URLMapping) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *URLMapping) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type APIShortenBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrls []*ShortURLMapping `protobuf:"bytes,1,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
}

func (x *APIShortenBatchResponse) Reset() {
	*x = APIShortenBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIShortenBatchResponse) ProtoMessage() {}

func (x *APIShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*APIShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{8}
}

func (x *APIShortenBatchResponse) GetShortUrls() []*ShortURLMapping {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

type ShortURLMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortURLMapping) Reset() {
	*x = ShortURLMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLMapping) ProtoMessage() {}

func (x *ShortURLMapping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLMapping.ProtoReflect.Descriptor instead.
func (*ShortURLMapping) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{9}
}

func (x *ShortURLMapping) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortURLMapping) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type APIShortenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *APIShortenResponse) Reset() {
	*x = APIShortenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIShortenResponse) ProtoMessage() {}

func (x *APIShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIShortenResponse.ProtoReflect.Descriptor instead.
func (*APIShortenResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{10}
}

func (x *APIShortenResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type APIUserAllURLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIUserAllURLsRequest) Reset() {
	*x = APIUserAllURLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIUserAllURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIUserAllURLsRequest) ProtoMessage() {}

func (x *APIUserAllURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIUserAllURLsRequest.ProtoReflect.Descriptor instead.
func (*APIUserAllURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{11}
}

type APIUserAllURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*URLMapping `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *APIUserAllURLsResponse) Reset() {
	*x = APIUserAllURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIUserAllURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIUserAllURLsResponse) ProtoMessage() {}

func (x *APIUserAllURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIUserAllURLsResponse.ProtoReflect.Descriptor instead.
func (*APIUserAllURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{12}
}

func (x *APIUserAllURLsResponse) GetUrls() []*URLMapping {
	if x != nil {
		return x.Urls
	}
	return nil
}

type APIDeleteUrlsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *APIDeleteUrlsRequest) Reset() {
	*x = APIDeleteUrlsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIDeleteUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDeleteUrlsRequest) ProtoMessage() {}

func (x *APIDeleteUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDeleteUrlsRequest.ProtoReflect.Descriptor instead.
func (*APIDeleteUrlsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{13}
}

func (x *APIDeleteUrlsRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type APIDeleteUrlsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *APIDeleteUrlsResponse) Reset() {
	*x = APIDeleteUrlsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIDeleteUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDeleteUrlsResponse) ProtoMessage() {}

func (x *APIDeleteUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDeleteUrlsResponse.ProtoReflect.Descriptor instead.
func (*APIDeleteUrlsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{14}
}

func (x *APIDeleteUrlsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type APIInternalStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIInternalStatsRequest) Reset() {
	*x = APIInternalStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIInternalStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIInternalStatsRequest) ProtoMessage() {}

func (x *APIInternalStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIInternalStatsRequest.ProtoReflect.Descriptor instead.
func (*APIInternalStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{15}
}

type APIInternalStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users int32 `protobuf:"varint,1,opt,name=users,proto3" json:"users,omitempty"`
	Urls  int32 `protobuf:"varint,2,opt,name=urls,proto3" json:"urls,omitempty"`
}

func (x *APIInternalStatsResponse) Reset() {
	*x = APIInternalStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIInternalStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIInternalStatsResponse) ProtoMessage() {}

func (x *APIInternalStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIInternalStatsResponse.ProtoReflect.Descriptor instead.
func (*APIInternalStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{16}
}

func (x *APIInternalStatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *APIInternalStatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

type TokenHandlerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *TokenHandlerRequest) Reset() {
	*x = TokenHandlerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenHandlerRequest) ProtoMessage() {}

func (x *TokenHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenHandlerRequest.ProtoReflect.Descriptor instead.
func (*TokenHandlerRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{17}
}

func (x *TokenHandlerRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenHandlerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *TokenHandlerResponse) Reset() {
	*x = TokenHandlerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shortner_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenHandlerResponse) ProtoMessage() {}

func (x *TokenHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortner_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenHandlerResponse.ProtoReflect.Descriptor instead.
func (*TokenHandlerResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortner_proto_rawDescGZIP(), []int{18}
}

func (x *TokenHandlerResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_shortner_proto protoreflect.FileDescriptor

var file_proto_shortner_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a,
	0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x0c,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x25, 0x0a, 0x11, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x31, 0x0a,
	0x12, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c,
	0x22, 0x30, 0x0a, 0x11, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x55, 0x52, 0x4c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4b,
	0x65, 0x79, 0x22, 0x2f, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c,
	0x55, 0x72, 0x6c, 0x22, 0x3f, 0x0a, 0x16, 0x41, 0x50, 0x49, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x22, 0x56, 0x0a, 0x0a, 0x55, 0x52, 0x4c, 0x4d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x50, 0x0a, 0x17,
	0x41, 0x50, 0x49, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x55,
	0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x31, 0x0a, 0x12, 0x41, 0x50, 0x49, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x17, 0x0a, 0x15, 0x41, 0x50, 0x49, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3f, 0x0a, 0x16, 0x41, 0x50, 0x49, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x55,
	0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x75,
	0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x75, 0x72,
	0x6c, 0x73, 0x22, 0x2a, 0x0a, 0x14, 0x41, 0x50, 0x49, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x72, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x31,
	0x0a, 0x15, 0x41, 0x50, 0x49, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x19, 0x0a, 0x17, 0x41, 0x50, 0x49, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x18,
	0x41, 0x50, 0x49, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x75, 0x72,
	0x6c, 0x73, 0x22, 0x2b, 0x0a, 0x13, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x2c, 0x0a, 0x14, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0xe2, 0x04,
	0x0a, 0x0e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x31, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0a, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x54, 0x6f, 0x55, 0x52, 0x4c, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x54, 0x6f,
	0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a,
	0x0f, 0x41, 0x50, 0x49, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x50, 0x49, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x50, 0x49, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x41, 0x50, 0x49, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x55,
	0x52, 0x4c, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x50, 0x49, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x50, 0x49, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0d, 0x41, 0x50, 0x49, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x72, 0x6c, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x50, 0x49, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x50, 0x49, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x55, 0x0a, 0x10, 0x41, 0x50, 0x49, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x50, 0x49,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x50, 0x49,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61,
	0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_shortner_proto_rawDescOnce sync.Once
	file_proto_shortner_proto_rawDescData = file_proto_shortner_proto_rawDesc
)

func file_proto_shortner_proto_rawDescGZIP() []byte {
	file_proto_shortner_proto_rawDescOnce.Do(func() {
		file_proto_shortner_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_shortner_proto_rawDescData)
	})
	return file_proto_shortner_proto_rawDescData
}

var file_proto_shortner_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_shortner_proto_goTypes = []interface{}{
	(*PingRequest)(nil),              // 0: proto.PingRequest
	(*PingResponse)(nil),             // 1: proto.PingResponse
	(*URLtoShortRequest)(nil),        // 2: proto.URLtoShortRequest
	(*URLtoShortResponse)(nil),       // 3: proto.URLtoShortResponse
	(*ShortToURLRequest)(nil),        // 4: proto.ShortToURLRequest
	(*ShortToURLResponse)(nil),       // 5: proto.ShortToURLResponse
	(*APIShortenBatchRequest)(nil),   // 6: proto.APIShortenBatchRequest
	(*URLMapping)(nil),               // 7: proto.URLMapping
	(*APIShortenBatchResponse)(nil),  // 8: proto.APIShortenBatchResponse
	(*ShortURLMapping)(nil),          // 9: proto.ShortURLMapping
	(*APIShortenResponse)(nil),       // 10: proto.APIShortenResponse
	(*APIUserAllURLsRequest)(nil),    // 11: proto.APIUserAllURLsRequest
	(*APIUserAllURLsResponse)(nil),   // 12: proto.APIUserAllURLsResponse
	(*APIDeleteUrlsRequest)(nil),     // 13: proto.APIDeleteUrlsRequest
	(*APIDeleteUrlsResponse)(nil),    // 14: proto.APIDeleteUrlsResponse
	(*APIInternalStatsRequest)(nil),  // 15: proto.APIInternalStatsRequest
	(*APIInternalStatsResponse)(nil), // 16: proto.APIInternalStatsResponse
	(*TokenHandlerRequest)(nil),      // 17: proto.TokenHandlerRequest
	(*TokenHandlerResponse)(nil),     // 18: proto.TokenHandlerResponse
}
var file_proto_shortner_proto_depIdxs = []int32{
	7,  // 0: proto.APIShortenBatchRequest.urls:type_name -> proto.URLMapping
	9,  // 1: proto.APIShortenBatchResponse.short_urls:type_name -> proto.ShortURLMapping
	7,  // 2: proto.APIUserAllURLsResponse.urls:type_name -> proto.URLMapping
	0,  // 3: proto.HandlerService.Ping:input_type -> proto.PingRequest
	2,  // 4: proto.HandlerService.URLtoShort:input_type -> proto.URLtoShortRequest
	4,  // 5: proto.HandlerService.ShortToURL:input_type -> proto.ShortToURLRequest
	6,  // 6: proto.HandlerService.APIShortenBatch:input_type -> proto.APIShortenBatchRequest
	11, // 7: proto.HandlerService.APIUserAllURLs:input_type -> proto.APIUserAllURLsRequest
	13, // 8: proto.HandlerService.APIDeleteUrls:input_type -> proto.APIDeleteUrlsRequest
	15, // 9: proto.HandlerService.APIInternalStats:input_type -> proto.APIInternalStatsRequest
	17, // 10: proto.HandlerService.TokenHandler:input_type -> proto.TokenHandlerRequest
	1,  // 11: proto.HandlerService.Ping:output_type -> proto.PingResponse
	3,  // 12: proto.HandlerService.URLtoShort:output_type -> proto.URLtoShortResponse
	5,  // 13: proto.HandlerService.ShortToURL:output_type -> proto.ShortToURLResponse
	8,  // 14: proto.HandlerService.APIShortenBatch:output_type -> proto.APIShortenBatchResponse
	12, // 15: proto.HandlerService.APIUserAllURLs:output_type -> proto.APIUserAllURLsResponse
	14, // 16: proto.HandlerService.APIDeleteUrls:output_type -> proto.APIDeleteUrlsResponse
	16, // 17: proto.HandlerService.APIInternalStats:output_type -> proto.APIInternalStatsResponse
	18, // 18: proto.HandlerService.TokenHandler:output_type -> proto.TokenHandlerResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_shortner_proto_init() }
func file_proto_shortner_proto_init() {
	if File_proto_shortner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_shortner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLtoShortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLtoShortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortToURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortToURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIShortenBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIShortenBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIShortenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIUserAllURLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIUserAllURLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIDeleteUrlsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIDeleteUrlsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIInternalStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIInternalStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenHandlerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shortner_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenHandlerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_shortner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortner_proto_goTypes,
		DependencyIndexes: file_proto_shortner_proto_depIdxs,
		MessageInfos:      file_proto_shortner_proto_msgTypes,
	}.Build()
	File_proto_shortner_proto = out.File
	file_proto_shortner_proto_rawDesc = nil
	file_proto_shortner_proto_goTypes = nil
	file_proto_shortner_proto_depIdxs = nil
}
